---
:api_key: ba7c0f32b037fbf61599cce853fec0e2
:password: 62bd5c24049876f412d98bca7f2d47b2
:store: gnarlacious.myshopify.com
:theme_id: 
:whitelist_files:
- layout/
- assets/
- config/
- snippets/
- templates/
- locales/
